---
#
# Installing Java 8
#
# Add the Java ppa repository
- name: Add Java repository
  apt_repository:
   repo: ppa:openjdk-r/ppa

# Automatically accepts the Oracle License popup in the terminal
- name: Automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

# Install Java 8
- name: Install Oracle openjdk-8-jdk
  apt:
   name: openjdk-8-jdk
   state: present
   update_cache: yes
