---
#
# Installing Elasticsearch
#
# Adds the apt-key for Elasticsearch
- name: Add Elasticsearch apt-key
  apt_key:
   url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
   state: present

- name: Check that HTTPS transport is available to APT
  apt: name="apt-transport-https" state=present

# Add the Elasticsearch APT-repository
- name: Adding Elasticsearch APT repository
  apt_repository:
   repo: "deb https://artifacts.elastic.co/packages/6.x/apt  stable main"
   state: present

# Install Elasticsearch
- name: Update repositories cache and install Elasticsearch
  apt:
   name: elasticsearch
   update_cache: yes

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    state: present

# Update Elasticsearch config file to only allow localhost connections
- name: Updating the config file to restrict outside access
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'network.host:'
   line: 'network.host: 127.0.0.1'

- name: open port
  lineinfile:
    path: /etc//elasticsearch/elasticsearch.yml
    regexp: '^http.port: 9200'

    line: 'http.port: 9200'
# Restart Elasticsearch
- name: stoping Elasticsearch
  service:
   name: elasticsearch
   state: stopped

# Restart Elasticsearch
- name: starting Elasticsearch
  service:
   name: elasticsearch
   state: started
